# Generated by Django 4.1.6 on 2023-05-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
